### Installing nginx webserver
- name: nginx installation
  yum:
   - name: epel-release
     state: latest
   - name: nginx1
     state: latest

- name: deploying website
  copy: 
    src: ./index.html
    dest: /usr/share/html/index.html
# - name: hosting website on 80
#   lineinfile:
#     path: /etc/httpd/conf/httpd.conf
#     regex: "^Listen 8080"
#     line: "Listen 80"
- name: start web service
  service:
    name: nginx
    state: restarted
    enabled: true