TOMCAT_URL: "https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.82/bin/apache-tomcat-8.5.82.tar.gz"
TOMCAT_ZIP: "{{ TOMCAT_URL | basename }}"
STUDENTAPP_URL: "s3://ansible-studentapp/student.war"
TOMCAT_DIR: "{{TOMCAT_ZIP | regex_replace('.tar.gz', '')}}"